@startuml
actor Пользователь
boundary Панель
boundary Слайдер
control Settings

Пользователь -> Панель : Изменить шаг
Панель -> Слайдер : min, max
Панель -> Слайдер : значение элемента input
Панель -> Слайдер : текущее значение из массива\nдопустимых значений шага
Слайдер -> Панель : если значение в элементе input\nбольше текущего значения,\nзначит нажали стрелочку "вверх"\nи переходим к следующему элементу массива
Слайдер -> Панель : если значение в элементе input\nменьше текущего значения,\nзначит нажали стрелочку "вверх"\nи переходим к предыдущему элементу массива
Settings -> Слайдер : порядковй номер слайдера
Слайдер -> Слайдер : makeScale()
note left
Перерасчёт параметров шкалы
end note
Слайдер -> Слайдер : reScale()
note left
Перестроение шкалы
end note
@enduml