@startuml
actor Пользователь
boundary Панель
boundary Слайдер
control Settings

Пользователь -> Панель : снять "галочку" \nв чекбоксе "Бегун"
note left
Работа слайдера
с двумя бегунками:
1. Пользователь отключает чекбокс
   "Бегун"
2. Наводит указатель мыши на бегунок
3. Нажимает левую кнопку мыши
4. Перемещает бегунок
5. Отпускает левую кнопку мыши
end note 
Панель -> Settings : runners = '2'
Слайдер -> Слайдер : hideTip()
note right
Отключение подписи над бегунками
end note
Панель -> Settings : btn1_coord = 0
note right
Обнуление текущих координат
end note
Панель -> Слайдер : tip = ''
note right
Обнуление надписи над бегунком
end note
Слайдер -> Слайдер : second_button = new Button();
note right
Создаю второй бегун
end note
Слайдер -> Слайдер : type = "btn_second"\ninst = номер слайдера на странице\ntip = ''
note right
Определение дата-атрибутов
для второго бегуна
end note
Панель -> Settings : btn2_coord = ranger.offsetWidth
note right
Текущие координаты второго
бегуна приравниваем
ширине слайдера
end note
Панель -> Settings : btn2_init_pos = ranger.offsetWidth
note right
Исходные координаты второго
бегуна приравниваем
ширине слайдера
end note
Слайдер -> Слайдер : interval.style.width = ranger.offsetWidth
note right
Прогрессбар во всю ширину слайдера
end note
Слайдер -> Слайдер : button_1.style.marginLeft = '0px';
note right
Первый бегунок - в
крайнюю левую позицию
end note
Слайдер -> Слайдер : button_2.style.marginLeft = ranger.offsetWidth - button_1.offsetWidth
note right
Второй бегунок - в
крайнюю правую позицию
end note
Пользователь -> Слайдер : Навести указатель мыши на бегунок
Пользователь -> Слайдер: Нажать левую клавишу мышки
Слайдер -> Слайдер : getCoords()
Пользователь -> Слайдер : Переместить бегунок
Слайдер -> Слайдер: discreteArray()
Слайдер -> Settings : btn1_coord,\nbtn1_tip
Слайдер -> Слайдер : interval.style.width \ninterval.style.marginLeft
Слайдер -> Слайдер  : btn1.style.marginLeft
Пользователь -> Слайдер : Отпустить левую клавишу мышки
@enduml