@startuml
actor Пользователь
boundary Панель
boundary Слайдер
control Settings

Пользователь -> Панель : Поставить \ снять "галочку"\nв чекбоксе "Ярлык"
note left
Показать \ скрыть
подпись над бегунком
end note 
Панель -> Слайдер : бегунку добавить (удалить) \nкласс ranger__button-tip
Пользователь -> Слайдер : Переместить бегунок
Слайдер -> Слайдер : forTip()
Слайдер <- Settings : btn1_tip (btn2_tip) =\n текущее значение

@enduml